name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up RVM
        run: |
          curl -sSL https://get.rvm.io | bash

      - name: Install Curl libraries
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libcurl4-openssl-dev build-essential

      - name: Set up Ruby from .ruby-version
        run: |
          source $HOME/.rvm/scripts/rvm
          rvm install $(cat .ruby-version) 
          rvm --default use $(cat .ruby-version)
          rvm use --create $(cat .ruby-version)@$(cat .ruby-gemset)

      - name: Build App
        run: |
          cp .env.github-actions .env
          source $HOME/.rvm/scripts/rvm
          rvm use $(cat .ruby-version)@$(cat .ruby-gemset)
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run Tests
        run: |
          source $HOME/.rvm/scripts/rvm
          rvm use $(cat .ruby-version)@$(cat .ruby-gemset)
          bundle exec rake test

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/.resultset.json
          format: simplecov

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
